BEGIN
  EXECUTE IMMEDIATE '
    CREATE TABLE debezium_signal (
      id VARCHAR2(42) PRIMARY KEY,
      type VARCHAR2(32) NOT NULL,
      data VARCHAR2(2048)
    )';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

ALTER TABLE debezium_signal ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
