CREATE TABLE products (
  product_id VARCHAR2(64) PRIMARY KEY,
  sku VARCHAR2(64) NOT NULL,
  product_name VARCHAR2(255) NOT NULL,
  product_category VARCHAR2(128) NOT NULL,
  supplier_id VARCHAR2(64) NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE suppliers (
  supplier_id VARCHAR2(64) PRIMARY KEY,
  supplier_name VARCHAR2(255) NOT NULL,
  country VARCHAR2(64) NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE stock_movements (
  movement_id VARCHAR2(64) PRIMARY KEY,
  product_id VARCHAR2(64) NOT NULL,
  warehouse_id VARCHAR2(64) NOT NULL,
  movement_type VARCHAR2(32) NOT NULL,
  quantity NUMBER(12) NOT NULL,
  movement_ts TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE debezium_signal (
  id VARCHAR2(42) PRIMARY KEY,
  type VARCHAR2(32) NOT NULL,
  data VARCHAR2(2048)
);

ALTER DATABASE ADD SUPPLEMENTAL LOG DATA;
ALTER TABLE products ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
ALTER TABLE suppliers ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
ALTER TABLE stock_movements ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
ALTER TABLE debezium_signal ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
