key.converter=org.apache.kafka.connect.json.JsonConverter
value.converter=org.apache.kafka.connect.json.JsonConverter
key.converter.schemas.enable=false
value.converter.schemas.enable=false
config.providers=secrets
config.providers.secrets.class=com.github.jcustenborder.kafka.config.aws.SecretsManagerConfigProvider
connector.client.config.override.policy=All
errors.tolerance=none
errors.log.enable=true
errors.log.include.messages=false
